@startuml
class Vehículo 
class Conductor 
class Horario 
class Empresa 
class Incidencia 
class Tarifa 
class Servicio 
abstract class MetodoPago
class Tarjeta
class Efectivo
class Pasajero 

Vehículo --> Conductor : Tiene
Vehículo --> Empresa : Pertenece
Empresa --> Incidencia : Gestiona
Conductor --> Horario : Sigue
Conductor --> Pasajero : Recoge
Pasajero --> Tarifa : Paga
Tarifa --> Servicio : Depende
Tarifa --> MetodoPago : Pagada con
Pasajero --> Vehículo : Suben
Servicio --> Horario : Programado en
Incidencia --> Vehículo : Asociada a
MetodoPago <|-- Tarjeta
MetodoPago <|-- Efectivo
@enduml
